### ISSUE TITLE
Cannot install the plugin with the suggested `pip` command

### ISSUE THREAD

**Issue by johnnovak** [blueswen/mkdocs-glightbox#12] opened 2022-12-12 08:24 UTC
I cannot install the plugin with the `pip install mkdocs-glightbox` command as suggested in the README. It appears that `pip` only displays a warning and the install was successful, but then the plugin is not in the installed package list, and `mkdocs` cannot find it:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/698770/206995506-a0ce3558-dbd1-42c3-aa14-5ccf2a5cbd1d.png">

<img width="860" alt="image" src="https://user-images.githubusercontent.com/698770/206995892-3356644b-166f-4910-91c2-fe8a2980040e.png">

The workaround is to install the plugin with the below command, but it took a while for me to figure this out:

```
pip install --use-pep517 mkdocs-glightbox
```

I'm using the following versions:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/698770/206995580-f78bc7ee-ecb9-4ac7-826f-18e0dad936c3.png">

**Comment by blueswen** [comment] 2022-12-13 10:28
Hi @johnnovak,

I can't reproduce this error on a clean Linux container(python:3.9.16-slim with pip 22.3.1). Could you provide your `setuptools` and `wheel` versions as follow?

```bash
pip list | grep "setuptools\|wheel"
```

**Comment by johnnovak** [comment] 2022-12-16 05:08
> I can't reproduce this error on a clean Linux container(python:3.9.16-slim with pip 22.3.1). Could you provide your `setuptools` and `wheel` versions as follow?

Sure thing. I'm on macOS + MacPorts, btw.

Looks like I don't have `wheel`.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/698770/208026855-cbc38161-1989-4188-9f5a-5f3e8d916393.png">

**Comment by blueswen** [comment] 2022-12-16 10:07
I just uploaded the package wheel to [PyPI](https://pypi.org/project/mkdocs-glightbox/#files). This issue should be fixed when the wheel file is provided.

**Comment by johnnovak** [comment] 2022-12-16 23:07
> I just uploaded the package wheel to [PyPI](https://pypi.org/project/mkdocs-glightbox/#files). This issue should be fixed when the wheel file is provided.

That apparently fixed it. I've just done an uninstall followed by an install, and it downloaded that `whl` fine and didn't complain about anything. I think we can consider this resolved then, cheers guys.

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/698770/208203091-fa50b6e2-1651-4d4b-8073-0bdaa112efd7.png">

**Closed** 2022-12-17 02:22 UTC
