### ISSUE TITLE
large image zoom is faulty since 0.3.0

### ISSUE THREAD

**Issue by lukaszgiez** [blueswen/mkdocs-glightbox#21] opened 2023-05-10 06:45 UTC
Im using material for mkdocs version 9.1.11 with your plugin, and a large image (for example, 3071 x 1896; 150dpi; 32bit; png) doesn't work well with zoom. On clicking the zoom icon,  the picture isn't enlarged. Instead it moves to the left. Sometimes it moves beyond the screen.

I tested with versions 0.2.1, 0.3.0 and the latest, and it only works as it should (zoom icon indeed blows up the image in the browser) in 0.2.1.
Is there an extra configuration option to be set which I am missing since 0.3.0 or is it a bug?

Tested in firefox and chrome.

**Comment by blueswen** [comment] 2023-05-10 13:55
Could you provide your `mkdocs.yaml` or reproducible repository?

**Comment by killergoalie** [comment] 2023-12-11 16:33
Can confirm, it looks like when you zoom it doesn't zoom to the point of the image you click but instead shifts the image left off screen.
With version 0.2.1 it will zoom but force to the right edge, shifting the image to the left.
Version 0.1.0, 0.2.0, 0.3.0, and 0.3.1, all seem to send the image off the screen to the left.  If I maximize my browser on my ultrawide monitor I can't see the zoomed image but when i click on the screen I can see the un-zoom effect of the image becoming smaller and coming from off screen from the left.

My doc is using a large resolution png file, roughly 10000x5400

**Comment by blueswen** [comment] 2023-12-30 15:00
Thanks for reporting this bug and providing a reproducible repository. This bug has been fixed in [v0.3.6](https://github.com/blueswen/mkdocs-glightbox/releases/tag/v0.3.6) by changing the default width from `100%` to `auto`, because `100%` width will cause zooming offset incorrectly.

**Closed** 2024-05-01 13:32 UTC
